version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypassword123
      MYSQL_DATABASE: belajar_reactjs_contact_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://user:password123@mysql:3306/belajar_reactjs_contact_management
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://159.223.32.198:3000

volumes:
  mysql_data: