version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: belajar_reactjs_contact_management
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://appuser:apppassword@mysql:3306/belajar_reactjs_contact_management
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  mysql-data:
